server:
  port: 8080
  servlet:
    context-path: /daibacbakery

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cake"
    username: root
    password: Vinh2005
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    logging-level: TRACE